# This is a basic workflow that is manually triggered

name: CI Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [main]
  pull_request:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: NPM Install
          run: npm ci
      
        - name: Integration Tests
          run: test-chrome
        
          
